### In this self learning session, I practiced how to work with numpy functions. I picked 5 different functions to master. They include: 
### Reshaping an Array, Arranging an Array, Deleting Function, Insert Function, Appending Function

### Let's get started

In [1]:
import numpy as np

### 1) Reshaping an array

In [2]:
New= np.array([[[9, 8, 7],
               [1, 2, 3],
               [7, 6, 5]],
               
              [[1, 3, 7],
              [8, 4, 6],
              [9, 0, 2]],
              
              [[2, 7, 3],
              [5, 1, 8],
              [9, 0, 6]]])

In [3]:
np.reshape(New, (9,1,3))

array([[[9, 8, 7]],

       [[1, 2, 3]],

       [[7, 6, 5]],

       [[1, 3, 7]],

       [[8, 4, 6]],

       [[9, 0, 2]],

       [[2, 7, 3]],

       [[5, 1, 8]],

       [[9, 0, 6]]])

In [4]:
np.reshape(New, (1,3,9))

array([[[9, 8, 7, 1, 2, 3, 7, 6, 5],
        [1, 3, 7, 8, 4, 6, 9, 0, 2],
        [2, 7, 3, 5, 1, 8, 9, 0, 6]]])

In [5]:
np.reshape(New, (1, 9, 3))

array([[[9, 8, 7],
        [1, 2, 3],
        [7, 6, 5],
        [1, 3, 7],
        [8, 4, 6],
        [9, 0, 2],
        [2, 7, 3],
        [5, 1, 8],
        [9, 0, 6]]])

In [6]:
np.reshape(New, (1,27))

array([[9, 8, 7, 1, 2, 3, 7, 6, 5, 1, 3, 7, 8, 4, 6, 9, 0, 2, 2, 7, 3, 5,
        1, 8, 9, 0, 6]])

In [7]:
np.reshape(New, (3, 9, 1))

array([[[9],
        [8],
        [7],
        [1],
        [2],
        [3],
        [7],
        [6],
        [5]],

       [[1],
        [3],
        [7],
        [8],
        [4],
        [6],
        [9],
        [0],
        [2]],

       [[2],
        [7],
        [3],
        [5],
        [1],
        [8],
        [9],
        [0],
        [6]]])

In [8]:
Nums = np.array([[3, 2, 4],
               [62, 25, 52],
                [12, 35, 97],
               [54, 26, 85]])

In [9]:
#The original array is a 4 by 3 matrix but we reshaped it into a 3 by 4 matrix
np.reshape(Nums, [3, 4])

array([[ 3,  2,  4, 62],
       [25, 52, 12, 35],
       [97, 54, 26, 85]])

In [10]:
np.reshape(Nums, [6, 2])

array([[ 3,  2],
       [ 4, 62],
       [25, 52],
       [12, 35],
       [97, 54],
       [26, 85]])

In [11]:
#We can also create subsets which gives us a 3 dimensional array
np.reshape(Nums, [3,1,4])

array([[[ 3,  2,  4, 62]],

       [[25, 52, 12, 35]],

       [[97, 54, 26, 85]]])

In [12]:
#This didnt work because 10 is fixed number but the 10 needed to be defined/arranged in a list before using the command
np.reshape(10, [2,2])

ValueError: cannot reshape array of size 1 into shape (2,2)

### 2). Arranging and Reshaping an Array

In [13]:
a = 10
np.arange(a)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
#Let's now reshape the array into our desired matrix
np.arange(a).reshape([2,5])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [15]:
b= np.arange(20)
np.reshape(b, [5,4])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [16]:
np.arange(10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [17]:
#This did not work because the shape (2,4) cannot contain 20 numbers
np.arange(20).reshape(2,4)

ValueError: cannot reshape array of size 20 into shape (2,4)

In [18]:
np.arange(35).reshape(5, 7).reshape(7, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [19]:
#This arranges the numbers from 1 to 27 with increment of 3 
np.arange(1, 27, 3)

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25])

In [20]:
np.arange(1, 27, 3).reshape([3,3])

array([[ 1,  4,  7],
       [10, 13, 16],
       [19, 22, 25]])

In [21]:
#This arranges the numbers from 1 to 81 with increment of 3 and reshapes it into a 3D array 
np.arange(1, 81, 3).reshape([3, 3, 3])

array([[[ 1,  4,  7],
        [10, 13, 16],
        [19, 22, 25]],

       [[28, 31, 34],
        [37, 40, 43],
        [46, 49, 52]],

       [[55, 58, 61],
        [64, 67, 70],
        [73, 76, 79]]])

In [22]:
np.arange(30).reshape(3, 10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [23]:
b = np.arange(2, 60, 3)

In [24]:
b.shape

(20,)

In [25]:
np.reshape(b, [4,5])

array([[ 2,  5,  8, 11, 14],
       [17, 20, 23, 26, 29],
       [32, 35, 38, 41, 44],
       [47, 50, 53, 56, 59]])

In [26]:
np.arange(2, 30, 5).reshape(2,3)

array([[ 2,  7, 12],
       [17, 22, 27]])

In [27]:
Array=np.array([[[23, 73, 63],
              [36, 54, 85],
              [53, 73, 26]],
              
              [[24, 94, 84],
              [12, 74, 98],
              [85, 67, 90]],
              
              [[21, 87, 53],
              [11, 72, 10],
              [80, 77, 34]]])

In [28]:
Array[1, 2, 1]

67

In [29]:
np.reshape(Array, [3,9])

array([[23, 73, 63, 36, 54, 85, 53, 73, 26],
       [24, 94, 84, 12, 74, 98, 85, 67, 90],
       [21, 87, 53, 11, 72, 10, 80, 77, 34]])

In [30]:
np.reshape(Array, (9,3))

array([[23, 73, 63],
       [36, 54, 85],
       [53, 73, 26],
       [24, 94, 84],
       [12, 74, 98],
       [85, 67, 90],
       [21, 87, 53],
       [11, 72, 10],
       [80, 77, 34]])

In [31]:
np.reshape(Array, [3, 1, 9])

array([[[23, 73, 63, 36, 54, 85, 53, 73, 26]],

       [[24, 94, 84, 12, 74, 98, 85, 67, 90]],

       [[21, 87, 53, 11, 72, 10, 80, 77, 34]]])

In [32]:
np.reshape(Array, [9, 1, 3])

array([[[23, 73, 63]],

       [[36, 54, 85]],

       [[53, 73, 26]],

       [[24, 94, 84]],

       [[12, 74, 98]],

       [[85, 67, 90]],

       [[21, 87, 53]],

       [[11, 72, 10]],

       [[80, 77, 34]]])

In [33]:
len(Array)

3

### 3). Deleting an array - numpy.delete("array name", sub-array/list, axis)

Axis (0) = entire list 

In [34]:
New= np.array([[[9, 8, 7],
               [1, 2, 3],
               [7, 6, 5]],
               
              [[1, 3, 7],
              [8, 4, 6],
              [9, 0, 2]],
              
              [[2, 7, 3],
              [5, 1, 8],
              [9, 0, 6]]])

In [35]:
New.shape

(3, 3, 3)

In [36]:
# This delete function (New, "list Number", 0) removes the entire sub-list 1 from the array
np.delete(New, 0, 0)

array([[[1, 3, 7],
        [8, 4, 6],
        [9, 0, 2]],

       [[2, 7, 3],
        [5, 1, 8],
        [9, 0, 6]]])

In [37]:
# This delete function (New, "list Number", 0) removes the second sub-list from the array
np.delete(New, 1, 0)

array([[[9, 8, 7],
        [1, 2, 3],
        [7, 6, 5]],

       [[2, 7, 3],
        [5, 1, 8],
        [9, 0, 6]]])

In [38]:
# This delete function (New, "list Number", 0) removes the entire 3rd sub-list/array
np.delete(New, 2, 0)

array([[[9, 8, 7],
        [1, 2, 3],
        [7, 6, 5]],

       [[1, 3, 7],
        [8, 4, 6],
        [9, 0, 2]]])

In [39]:
New

array([[[9, 8, 7],
        [1, 2, 3],
        [7, 6, 5]],

       [[1, 3, 7],
        [8, 4, 6],
        [9, 0, 2]],

       [[2, 7, 3],
        [5, 1, 8],
        [9, 0, 6]]])

In [40]:
# This delete function (New, 0, 1) removes the first row in each subarray along the horizontal X-axis
np.delete(New, 0, 1 )

array([[[1, 2, 3],
        [7, 6, 5]],

       [[8, 4, 6],
        [9, 0, 2]],

       [[5, 1, 8],
        [9, 0, 6]]])

In [41]:
# This delete function (New, 1, 1) removes the second row in each subarray along the horizontal, X-axis
np.delete(New, 1, 1)

array([[[9, 8, 7],
        [7, 6, 5]],

       [[1, 3, 7],
        [9, 0, 2]],

       [[2, 7, 3],
        [9, 0, 6]]])

In [42]:
# This delete function (New, 0, 1) removes the third row in each subarray along the horizontal, X-axis
np.delete(New, 2, 1)

array([[[9, 8, 7],
        [1, 2, 3]],

       [[1, 3, 7],
        [8, 4, 6]],

       [[2, 7, 3],
        [5, 1, 8]]])

In [43]:
#AxisError: axis 3 is out of bounds for array of dimension 3
#This function did not work because we only have three axis (0= entire, 1=x-axis, 2 =y-axis)

np.delete(New, 0, 3)

AxisError: axis 3 is out of bounds for array of dimension 3

In [44]:
New

array([[[9, 8, 7],
        [1, 2, 3],
        [7, 6, 5]],

       [[1, 3, 7],
        [8, 4, 6],
        [9, 0, 2]],

       [[2, 7, 3],
        [5, 1, 8],
        [9, 0, 6]]])

In [45]:
# This delete function (New, 0, 1) removes the first column in each subarray along the vertical, y-axis
np.delete(New, 0, 2)

array([[[8, 7],
        [2, 3],
        [6, 5]],

       [[3, 7],
        [4, 6],
        [0, 2]],

       [[7, 3],
        [1, 8],
        [0, 6]]])

In [46]:
# This delete function (New, 0, 1) removes the second column in each subarray along the vertical, y-axis
np.delete(New, 1, 2)

array([[[9, 7],
        [1, 3],
        [7, 5]],

       [[1, 7],
        [8, 6],
        [9, 2]],

       [[2, 3],
        [5, 8],
        [9, 6]]])

In [47]:
# This delete function (New, 0, 1) removes the third column in each subarray along the vertical, y-axis
np.delete(New, 2, 2)

array([[[9, 8],
        [1, 2],
        [7, 6]],

       [[1, 3],
        [8, 4],
        [9, 0]],

       [[2, 7],
        [5, 1],
        [9, 0]]])

In [48]:
New

array([[[9, 8, 7],
        [1, 2, 3],
        [7, 6, 5]],

       [[1, 3, 7],
        [8, 4, 6],
        [9, 0, 2]],

       [[2, 7, 3],
        [5, 1, 8],
        [9, 0, 6]]])

In [49]:
np.reshape(New, [9, 3])

array([[9, 8, 7],
       [1, 2, 3],
       [7, 6, 5],
       [1, 3, 7],
       [8, 4, 6],
       [9, 0, 2],
       [2, 7, 3],
       [5, 1, 8],
       [9, 0, 6]])

In [50]:
np.delete(New, [1, 2, 3])

array([9, 2, 3, 7, 6, 5, 1, 3, 7, 8, 4, 6, 9, 0, 2, 2, 7, 3, 5, 1, 8, 9,
       0, 6])

In [51]:
np.delete(New, 1, 2)

array([[[9, 7],
        [1, 3],
        [7, 5]],

       [[1, 7],
        [8, 6],
        [9, 2]],

       [[2, 3],
        [5, 8],
        [9, 6]]])

### 4). Inserting new items into an array - numpy.insert("arrayname", "position", "new list/array", axis)
To insert, 

In [52]:
New

array([[[9, 8, 7],
        [1, 2, 3],
        [7, 6, 5]],

       [[1, 3, 7],
        [8, 4, 6],
        [9, 0, 2]],

       [[2, 7, 3],
        [5, 1, 8],
        [9, 0, 6]]])

In [53]:
#This function inserts 0 all thru into the third column of each list along the vertical, y-axis
np.insert(New, 2, 0, 2)

array([[[9, 8, 0, 7],
        [1, 2, 0, 3],
        [7, 6, 0, 5]],

       [[1, 3, 0, 7],
        [8, 4, 0, 6],
        [9, 0, 0, 2]],

       [[2, 7, 0, 3],
        [5, 1, 0, 8],
        [9, 0, 0, 6]]])

In [54]:
#This function inserts 2 all thru into the 3rd row of each list along the horizontal, x-axis
np.insert(New, 2, 2, 1)

array([[[9, 8, 7],
        [1, 2, 3],
        [2, 2, 2],
        [7, 6, 5]],

       [[1, 3, 7],
        [8, 4, 6],
        [2, 2, 2],
        [9, 0, 2]],

       [[2, 7, 3],
        [5, 1, 8],
        [2, 2, 2],
        [9, 0, 6]]])

In [55]:
#This function inserts [0, 1, 0] all thru into the 2nd row in each list along the horizontal, x-axis
np.insert(New, 1, [0, 1, 0], 1)

array([[[9, 8, 7],
        [0, 1, 0],
        [1, 2, 3],
        [7, 6, 5]],

       [[1, 3, 7],
        [0, 1, 0],
        [8, 4, 6],
        [9, 0, 2]],

       [[2, 7, 3],
        [0, 1, 0],
        [5, 1, 8],
        [9, 0, 6]]])

In [56]:
#This function inserts [24, 13, 56] all thru into first column in each list along the vertical, y-axis
np.insert(New, 0, [24, 13, 56], 2)

array([[[24,  9,  8,  7],
        [13,  1,  2,  3],
        [56,  7,  6,  5]],

       [[24,  1,  3,  7],
        [13,  8,  4,  6],
        [56,  9,  0,  2]],

       [[24,  2,  7,  3],
        [13,  5,  1,  8],
        [56,  9,  0,  6]]])

In [57]:
#This function inserts [6, 5, 9] as a 3 by 3 matrix into first position of list  in the array along the entire x and y axis
np.insert(New, 0, [6, 5, 9], 0)

array([[[6, 5, 9],
        [6, 5, 9],
        [6, 5, 9]],

       [[9, 8, 7],
        [1, 2, 3],
        [7, 6, 5]],

       [[1, 3, 7],
        [8, 4, 6],
        [9, 0, 2]],

       [[2, 7, 3],
        [5, 1, 8],
        [9, 0, 6]]])

In [58]:
#This function inserts [6, 5, 9] all thru as a third subarray along the entire x and y axis
np.insert(New, 2, [6, 5, 9], 0)

array([[[9, 8, 7],
        [1, 2, 3],
        [7, 6, 5]],

       [[1, 3, 7],
        [8, 4, 6],
        [9, 0, 2]],

       [[6, 5, 9],
        [6, 5, 9],
        [6, 5, 9]],

       [[2, 7, 3],
        [5, 1, 8],
        [9, 0, 6]]])

### Little Practice

In [59]:
New

array([[[9, 8, 7],
        [1, 2, 3],
        [7, 6, 5]],

       [[1, 3, 7],
        [8, 4, 6],
        [9, 0, 2]],

       [[2, 7, 3],
        [5, 1, 8],
        [9, 0, 6]]])

In [60]:
np.reshape(New, [3,9])

array([[9, 8, 7, 1, 2, 3, 7, 6, 5],
       [1, 3, 7, 8, 4, 6, 9, 0, 2],
       [2, 7, 3, 5, 1, 8, 9, 0, 6]])

In [61]:
np.delete(New, 1, 2)

array([[[9, 7],
        [1, 3],
        [7, 5]],

       [[1, 7],
        [8, 6],
        [9, 2]],

       [[2, 3],
        [5, 8],
        [9, 6]]])

In [67]:
j =np.insert(New, 2, (2, 9, 4), 2)
g =np.insert(New, 2, [1, 5, 2], 1)

In [68]:
len(j)

3

In [69]:
New

array([[[9, 8, 7],
        [1, 2, 3],
        [7, 6, 5]],

       [[1, 3, 7],
        [8, 4, 6],
        [9, 0, 2]],

       [[2, 7, 3],
        [5, 1, 8],
        [9, 0, 6]]])

In [70]:
j

array([[[9, 8, 2, 7],
        [1, 2, 9, 3],
        [7, 6, 4, 5]],

       [[1, 3, 2, 7],
        [8, 4, 9, 6],
        [9, 0, 4, 2]],

       [[2, 7, 2, 3],
        [5, 1, 9, 8],
        [9, 0, 4, 6]]])

In [71]:
g

array([[[9, 8, 7],
        [1, 2, 3],
        [1, 5, 2],
        [7, 6, 5]],

       [[1, 3, 7],
        [8, 4, 6],
        [1, 5, 2],
        [9, 0, 2]],

       [[2, 7, 3],
        [5, 1, 8],
        [1, 5, 2],
        [9, 0, 6]]])

In [72]:
np.delete(j, 2, 2)

array([[[9, 8, 7],
        [1, 2, 3],
        [7, 6, 5]],

       [[1, 3, 7],
        [8, 4, 6],
        [9, 0, 2]],

       [[2, 7, 3],
        [5, 1, 8],
        [9, 0, 6]]])

### 5). Append function

In [73]:
New

array([[[9, 8, 7],
        [1, 2, 3],
        [7, 6, 5]],

       [[1, 3, 7],
        [8, 4, 6],
        [9, 0, 2]],

       [[2, 7, 3],
        [5, 1, 8],
        [9, 0, 6]]])

In [74]:
a =np.append(New, 3)

In [75]:
a

array([9, 8, 7, 1, 2, 3, 7, 6, 5, 1, 3, 7, 8, 4, 6, 9, 0, 2, 2, 7, 3, 5,
       1, 8, 9, 0, 6, 3])

In [76]:
len(a)

28

In [78]:
#This did not work because the arrangement [6,5] can only contain 30 elements and the variable a has only 28
np.reshape(a, [6, 5])

ValueError: cannot reshape array of size 28 into shape (6,5)

In [79]:
np.reshape(a, [4, 7])

array([[9, 8, 7, 1, 2, 3, 7],
       [6, 5, 1, 3, 7, 8, 4],
       [6, 9, 0, 2, 2, 7, 3],
       [5, 1, 8, 9, 0, 6, 3]])

In [80]:
np.reshape(a, [7, 1, 4])

array([[[9, 8, 7, 1]],

       [[2, 3, 7, 6]],

       [[5, 1, 3, 7]],

       [[8, 4, 6, 9]],

       [[0, 2, 2, 7]],

       [[3, 5, 1, 8]],

       [[9, 0, 6, 3]]])

In [81]:
np.reshape(a, [4, 1, 7])

array([[[9, 8, 7, 1, 2, 3, 7]],

       [[6, 5, 1, 3, 7, 8, 4]],

       [[6, 9, 0, 2, 2, 7, 3]],

       [[5, 1, 8, 9, 0, 6, 3]]])