### In this notebook is a practice of what I first learned using Numpy

In [1]:
import numpy as np

### To sum up a 1Dimensional Array

In [2]:
array = [23, 53, 63]

In [3]:
job = np.array(array)

In [4]:
(job).sum()

139

### To Calculate the time/duration it takes to compute a code

In [5]:
num_1 = list(range(10))
num_2= list(range(1000,2000000))

In [6]:
Num_1 = np.array(num_1)
Num_2 = np.array(num_2)

In [7]:
%%time
result = 0
for x, y in zip(num_1, num_2):
    result += x*y
result

CPU times: total: 0 ns
Wall time: 0 ns


45285

In [8]:
%%time
np.dot(Num_1, Num_2)

ValueError: shapes (10,) and (1999000,) not aligned: 10 (dim 0) != 1999000 (dim 0)

### Types of Arrays

In [9]:
#This is a 1D array
Num_array1 = np.array([241, 26, 152])

#This is a 2D array
Num_array2 = np.array([[4.3, 53, 241],
                      [23, 3.4, 26],
                      [36, 36, 7.3]])

#This is a 3D array
Num_array3 = np.array([[[61, 57, 37],
                      [54, 47, 53]],
                      [[43, 64, 82],
                      [24, 72, 83]]])


### To Check the data type of numpy arrays use "data.dtype"

In [10]:
Num_array1.dtype

dtype('int32')

In [11]:
Num_array2.dtype

dtype('float64')

### To Check the shape of numpy arrays use "data.shape"

In [12]:
Num_array1.shape

(3,)

In [13]:
Num_array2.shape

(3, 3)

In [14]:
Num_array3.shape

(2, 2, 3)

In [15]:
Num_array4 = np.array([[[61, 57, 37],
                      [54, 47, 53],
                      [43, 64, 82],
                      [24, 72, 83]],
                     
                     [[63, 57, 37],
                      [54, 45, 53],
                      [43, 61, 82],
                      [24, 72, 53]]])

In [16]:
Num_array4.shape

(2, 4, 3)

In [17]:
Num_array5 = np.array([[[61, 57],
                      [54, 47],
                      [43, 64,]],
                     
                     [[63, 37],
                      [54, 53],
                      [24, 72]],
                      
                      [[32, 36],
                      [43, 74],
                      [54, 85]],
                      
                      [[23, 16],
                      [54, 89],
                      [42, 90]]])

In [18]:
Num_array5.shape

(4, 3, 2)

### To multiply two matrixes together use "np.matmul" or the "@" character

In [19]:
np.matmul(Num_array2, Num_array1)

array([39046.3,  9583.4, 10721.6])

In [20]:
Num_array2 @ Num_array1

array([39046.3,  9583.4, 10721.6])

In [21]:
No_1 = np.array([[34, 36, 25],
               [45, 32, 24],
               [86, 78, 8]])
No_2 = np.array([[54, 36, 24],
               [48, 53, 1],
               [86, 34, 8]])

### Arithmetic Operations and Comparison of Numpy arrays

In [22]:
No_1 + No_2 

array([[ 88,  72,  49],
       [ 93,  85,  25],
       [172, 112,  16]])

In [23]:
No_1 + 2

array([[36, 38, 27],
       [47, 34, 26],
       [88, 80, 10]])

In [24]:
No_2.shape

(3, 3)

In [25]:
No_1 == No_2

array([[False,  True, False],
       [False, False, False],
       [ True, False,  True]])

In [26]:
No_1 > No_2

array([[False, False,  True],
       [False, False,  True],
       [False,  True, False]])

In [27]:
No_2 >No_1

array([[ True, False, False],
       [ True,  True, False],
       [False, False, False]])

In [28]:
No_1 != No_2

array([[ True, False,  True],
       [ True,  True,  True],
       [False,  True, False]])

In [29]:
# This tells the number of elements that are equal in the both arrays(True =1 and False = 0)
(No_1 ==No_2).sum()

3

## Array and Indexing

In [30]:
No_1 = np.array([[34, 36, 25],
               [45, 32, 24],
               [86, 78, 8]])
No_2 = np.array([[54, 36, 24],
               [48, 53, 1],
               [86, 34, 8]])

In [31]:
No_1[2,1]

78

In [32]:
New_array = np.array([[[54, 36, 24],
                        [48, 53, 1],
                        [86, 34, 8],
                        [24, 72, 83]],
                     
                     [[63, 57, 37],
                      [54, 45, 53],
                      [43, 61, 82],
                      [24, 72, 53]]])

New_array1 = np.array([[[61, 57],
                      [54, 42],
                      [93, 64,]],
                     
                     [[63, 37],
                      [52, 53],
                      [24, 72]],
                      
                      [[32, 30],
                      [43, 74],
                      [51, 85]],
                      
                      [[45, 16],
                      [54, 85],
                      [42, 92]]])

In [33]:
New_array1[0:, 2, :1]

array([[93],
       [24],
       [51],
       [42]])

In [34]:
New_array1[1:, 1, 1]

array([53, 74, 85])

In [35]:
New_array[0:, 2]

array([[86, 34,  8],
       [43, 61, 82]])

In [36]:
New_array[0:, 2, 2]

array([ 8, 82])

In [37]:
New_array[0, 0:2]

array([[54, 36, 24],
       [48, 53,  1]])

In [38]:
New_array[0, 2:4]

array([[86, 34,  8],
       [24, 72, 83]])

In [39]:
New_array[0, 2:4, :2]

array([[86, 34],
       [24, 72]])

In [40]:
New_array[1,1]

array([54, 45, 53])

In [41]:
New_array[1, 2, 2]

82

In [42]:
New_array1[0, 2]

array([93, 64])

### Creating a Matrix

In [43]:
#all Zeros
np.zeros((3, 3, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [44]:
#All ones
np.ones((3, 2, 3))

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [45]:
#All Fives
np.full([3,4], 5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [46]:
#All Nines
np.full([3,3,2], 9)

array([[[9, 9],
        [9, 9],
        [9, 9]],

       [[9, 9],
        [9, 9],
        [9, 9]],

       [[9, 9],
        [9, 9],
        [9, 9]]])

In [47]:
import numpy as np

In [48]:
#Identity Matrix
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [49]:
#Randon Vector - gives matrix of random values
np.random.rand(12)

array([0.57773544, 0.04290984, 0.18172865, 0.98257962, 0.76309343,
       0.19748741, 0.73191718, 0.6357707 , 0.79595602, 0.73444516,
       0.9109827 , 0.41137107])

In [50]:
#Randon Vector with "n"- give matrix of random value from guassian expression
np.random.randn(5, 2, 4)

array([[[-0.83934519, -1.39274385, -0.00497795, -0.64121804],
        [-0.90034665,  0.44412774,  0.13679128,  1.61584346]],

       [[ 0.74525211, -1.39446676, -1.50130215, -1.90499752],
        [ 1.19502892,  0.26000652, -0.06714964,  0.9216227 ]],

       [[ 0.04262735,  0.85776675,  1.07203705,  0.35007755],
        [ 0.09311482,  1.56467122,  0.29355983, -0.84449052]],

       [[ 0.36100988,  1.13778603,  0.90554919, -0.45168154],
        [-1.00854868, -0.45705219, -0.32554733, -0.00195127]],

       [[-0.56235611, -0.96078661, -0.12188415,  1.16980305],
        [ 0.05262139, -0.85352597,  0.92838388, -0.57712614]]])

In [51]:
#To write a range with (start, end and step)
np.arange(2, 42, 2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40])

In [52]:
# This helps to know the number of elements in the array
np.arange(2, 42, 2).shape

(20,)

In [53]:
#This helps you shape your document into matrix form
np.arange(2, 42, 2).reshape(2, 2, 5)

array([[[ 2,  4,  6,  8, 10],
        [12, 14, 16, 18, 20]],

       [[22, 24, 26, 28, 30],
        [32, 34, 36, 38, 40]]])

In [54]:
#This helps you split your range of numbers into your desired number of list - range (start, end, list NO)
np.linspace(2, 20, 10)

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])