### In this notebook is a practice of what I first learned using Numpy

In [1]:
import numpy as np

### To sum up a 1Dimensional Array

In [2]:
array = [23, 53, 63]

In [3]:
job = np.array(array)

In [4]:
(job).sum()

139

### To Calculate the time/duration it takes to compute a code

In [5]:
num_1 = list(range(10))
num_2= list(range(1000,2000000))

In [6]:
Num_1 = np.array(num_1)
Num_2 = np.array(num_2)

In [7]:
%%time
result = 0
for x, y in zip(num_1, num_2):
    result += x*y
result

CPU times: total: 31.2 ms
Wall time: 998 µs


45285

### Types of Arrays

In [8]:
#This is a 1D array
Num_array1 = np.array([241, 26, 152])

#This is a 2D array
Num_array2 = np.array([[4.3, 53, 241],
                      [23, 3.4, 26],
                      [36, 36, 7.3]])

#This is a 3D array
Num_array3 = np.array([[[61, 57, 37],
                      [54, 47, 53]],
                      [[43, 64, 82],
                      [24, 72, 83]]])


### To Check the data type of numpy arrays use "data.dtype"

In [9]:
Num_array1.dtype

dtype('int32')

In [10]:
Num_array2.dtype

dtype('float64')

### To Check the shape of numpy arrays use "data.shape"

In [11]:
#The result shows that we have a row with 3 columns
Num_array1.shape

(3,)

In [12]:
#This shows that the array has 3 rows and 3 columns
Num_array2.shape

(3, 3)

In [13]:
# This shows that we has 2 lists, 2 rows and 3 columns in each of the lists
Num_array3.shape

(2, 2, 3)

In [14]:
Num_array4 = np.array([[[61, 57, 37],
                      [54, 47, 53],
                      [43, 64, 82],
                      [24, 72, 83]],
                     
                     [[63, 57, 37],
                      [54, 45, 53],
                      [43, 61, 82],
                      [24, 72, 53]]])

In [15]:
#The result shows that Num_array4 has 2 lists, with each having 4 row with 3 columns
Num_array4.shape

(2, 4, 3)

In [16]:
Num_array5 = np.array([[[61, 57],
                      [54, 47],
                      [43, 64,]],
                     
                     [[63, 37],
                      [54, 53],
                      [24, 72]],
                      
                      [[32, 36],
                      [43, 74],
                      [54, 85]],
                      
                      [[23, 16],
                      [54, 89],
                      [42, 90]]])

In [17]:
#The result shows that Num_array5 has 4 lists, with each having 3 row with 2 columns
Num_array5.shape

(4, 3, 2)

### To multiply two matrixes together use "np.matmul" or the "@" character

In [18]:
#Method 1
np.matmul(Num_array2, Num_array1)

array([39046.3,  9583.4, 10721.6])

In [19]:
#Method 2
Num_array2 @ Num_array1

array([39046.3,  9583.4, 10721.6])

### Arithmetic Operations and Comparison of Numpy arrays

In [20]:
No_1 = np.array([[34, 36, 25],
               [45, 32, 24],
               [86, 78, 8]])
No_2 = np.array([[54, 36, 24],
               [48, 53, 1],
               [86, 34, 8]])

In [21]:
#This adds the two matrices together
No_1 + No_2 

array([[ 88,  72,  49],
       [ 93,  85,  25],
       [172, 112,  16]])

In [22]:
#This adds 2 two each element of the array No_1
No_1 + 2

array([[36, 38, 27],
       [47, 34, 26],
       [88, 80, 10]])

In [23]:
#This tells us our array is a 3 by matrix i.e it has 3 rows and 3 columns
No_2.shape

(3, 3)

In [24]:
#This line of code compares the individual elements of the two array to find which of its elements are equal
No_1 == No_2

array([[False,  True, False],
       [False, False, False],
       [ True, False,  True]])

In [25]:
# This tells the number of elements that are equal in the both arrays. The results shows that there are only 3 equal elements(True =1 and False = 0)
(No_1 ==No_2).sum()

3

In [26]:
#This line of code compares the individual elements of the two array to find which of its elements in array1 is greater than those in array2
No_1 > No_2

array([[False, False,  True],
       [False, False,  True],
       [False,  True, False]])

In [27]:
#vice-versa
No_2 >No_1

array([[ True, False, False],
       [ True,  True, False],
       [False, False, False]])

In [28]:
#This line of code compares the individual elements of the two array to find which of its elements are NOT equal
No_1 != No_2

array([[ True, False,  True],
       [ True,  True,  True],
       [False,  True, False]])

## Array and Indexing

In [29]:
No_1 = np.array([[34, 36, 25],
               [45, 32, 24],
               [86, 78, 8]])
No_2 = np.array([[54, 36, 24],
               [48, 53, 1],
               [86, 34, 8]])

In [30]:
#This helps us access the element in the third row and second column of array No_1
No_1[2,1]

78

In [31]:
New_array = np.array([[[54, 36, 24],
                        [48, 53, 1],
                        [86, 34, 8],
                        [24, 72, 83]],
                     
                     [[63, 57, 37],
                      [54, 45, 53],
                      [43, 61, 82],
                      [24, 72, 53]]])

New_array1 = np.array([[[61, 57],
                      [54, 42],
                      [93, 64,]],
                     
                     [[63, 37],
                      [52, 53],
                      [24, 72]],
                      
                      [[32, 30],
                      [43, 74],
                      [51, 85]],
                      
                      [[45, 16],
                      [54, 85],
                      [42, 92]]])

In [32]:
#say we want to get all the elements from the 1st column before the 2nd column in the 3rd row of each lists
New_array1[0:, 2, :1]

array([[93],
       [24],
       [51],
       [42]])

In [33]:
#This code gives us the 2nd element of the 2nd row from the second list to the last list in the array
New_array1[1:, 1, 1]

array([53, 74, 85])

In [34]:
New_array[0:, 2]

array([[86, 34,  8],
       [43, 61, 82]])

In [35]:
New_array[0:, 2, 2]

array([ 8, 82])

In [36]:
New_array[0, 0:2]

array([[54, 36, 24],
       [48, 53,  1]])

In [37]:
New_array[0, 2:4]

array([[86, 34,  8],
       [24, 72, 83]])

In [38]:
New_array


array([[[54, 36, 24],
        [48, 53,  1],
        [86, 34,  8],
        [24, 72, 83]],

       [[63, 57, 37],
        [54, 45, 53],
        [43, 61, 82],
        [24, 72, 53]]])

In [39]:
New_array[0, 0:2, 1:]

array([[36, 24],
       [53,  1]])

In [40]:
New_array[0, 2:4, :2]

array([[86, 34],
       [24, 72]])

In [41]:
New_array[1,1]

array([54, 45, 53])

In [42]:
New_array[1, 2, 2]

82

In [43]:
New_array1[0, 2]

array([93, 64])

### Creating a Matrix

In [44]:
#all Zeros
np.zeros((3, 3, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [45]:
#All ones
np.ones((3, 2, 3))

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [46]:
#All Fives
np.full([3,4], 5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [47]:
#All Nines
np.full([3,3,2], 9)

array([[[9, 9],
        [9, 9],
        [9, 9]],

       [[9, 9],
        [9, 9],
        [9, 9]],

       [[9, 9],
        [9, 9],
        [9, 9]]])

In [48]:
import numpy as np

In [49]:
#Identity Matrix
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [50]:
#Randon Vector - gives matrix of random values
np.random.rand(12)

array([0.49315681, 0.53253101, 0.24140161, 0.91136432, 0.6999704 ,
       0.71909327, 0.17939686, 0.23312723, 0.83387971, 0.72332756,
       0.03789644, 0.93106512])

In [51]:
#Randon Vector with "n"- give matrix of random value from guassian expression
np.random.randn(5, 2, 4)

array([[[ 1.28588067e+00, -6.44928601e-04,  4.78631565e-01,
          6.32307571e-01],
        [-9.24008474e-01, -2.41831595e-01, -1.13351283e+00,
          6.17324113e-01]],

       [[-1.19922642e+00,  1.43963819e+00,  5.07950968e-01,
          1.60545666e+00],
        [ 1.38836279e-01, -5.78209626e-01, -3.20846859e-01,
         -3.92366960e-01]],

       [[ 4.36765789e-01,  1.38522298e+00,  6.87258731e-01,
         -4.81327145e-01],
        [ 6.70526554e-01,  2.79232483e-01,  5.79317921e-01,
         -7.09819649e-01]],

       [[-1.05145636e+00,  6.69264821e-01, -1.26266735e+00,
         -5.89027400e-01],
        [ 1.11039420e+00,  4.73159009e-01,  9.43938884e-01,
          1.10648131e+00]],

       [[-1.02065525e-01, -5.30493010e-01, -4.82733849e-01,
         -4.15655813e-01],
        [-8.12237001e-01,  3.91733786e-01,  1.58659920e+00,
          3.55883299e-01]]])

In [52]:
#To write a range with (start, end and step)
np.arange(2, 42, 2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40])

In [53]:
# This helps to know the number of elements in the array
np.arange(2, 42, 2).shape

(20,)

In [54]:
#This helps you shape your document into matrix form
np.arange(2, 42, 2).reshape(2, 2, 5)

array([[[ 2,  4,  6,  8, 10],
        [12, 14, 16, 18, 20]],

       [[22, 24, 26, 28, 30],
        [32, 34, 36, 38, 40]]])

In [55]:
#This helps you split your range of numbers into your desired number of list - range (start, end, list NO)
np.linspace(2, 20, 10)

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])